server:
  port: 8090

spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://localhost:8088

  cloud:
    gateway:
      routes:
        # Public routes (no authentication required)
        - id: auth-service-public
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/login,/api/auth/register,/api/auth/generateToken
          filters:
            - name: Retry
              args:
                retries: 3
        
        # Protected routes (authentication required)
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/students/**
          filters:
            - name: JwtAuthenticationFilter
        
        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/courses/**
          filters:
            - name: JwtAuthenticationFilter
        
        - id: enrollment-service
          uri: lb://ENROLLMENT-SERVICE
          predicates:
            - Path=/api/enrollments/**
          filters:
            - name: JwtAuthenticationFilter
        
        # Auth service protected routes
        - id: auth-service-protected
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/validate,/api/auth/user/**
          filters:
            - name: JwtAuthenticationFilter
            
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowed-headers: "*"
            allow-credentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

# JWT Configuration
jwt:
  auth:
    converter:
      resource-id: api-gateway

# Feign Configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
      AUTH-SERVICE:
        connectTimeout: 3000
        readTimeout: 3000

# Logging configuration for debugging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.example.demo.filter: DEBUG
    com.example.demo.client: DEBUG
