server:
  port: 8088

spring:
  application:
    name: api-gateway


  webflux:
    cors:
      allowed-origins: "http://localhost:4200"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
      allowed-headers: "*"
      allow-credentials: true

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: student-service
              uri: lb://student-service
              predicates:
                - Path=/api/student/**
            - id: course-service
              uri: lb://course-service
              predicates:
                - Path=/api/course/**
            - id: enrollment-service
              uri: lb://enrollment-service
              predicates:
                - Path=/api/enrollment/**
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
      auth-service:
        connectTimeout: 3000
        readTimeout: 3000


