spring:
  application:
    name: enrollment-service
  datasource:
    url: jdbc:mysql://localhost:3306/practice_enrollmentdb?createDatabaseIfNotExist=true
    username: root
    password: cab_booking
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8086

management:
  endpoints:
    web:
    exposure:
      include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

springdoc:
  api:
    api-docs:
      path: /api/users/v3/api-docs
      swagger-ui:
        path: /api/users/swagger-ui.html
        operationsSorter: method
        tagsSorter: alpha


